* Problem Statement
  /The goal of this problem is to represent a given positive integer ğ‘› as a sum of as many pairwise
distinct positive integers as possible. That is, to find the maximum ğ‘˜ such that ğ‘› can be written as
ğ‘1 + ğ‘2 + Â· Â· Â· + ğ‘ğ‘˜ where ğ‘1, . . . , ğ‘ğ‘˜ are positive integers and ğ‘ğ‘– Ì¸= ğ‘ğ‘— for all 1 â‰¤ ğ‘– < ğ‘— â‰¤ ğ‘˜/

  - *Input:* The input consists of a single integer ğ‘›.
  - *Constraints:*  1 â‰¤ ğ‘› â‰¤ 10**9
  - *Output:* In the first line, output the maximum number ğ‘˜ such that ğ‘› can be represented as a sum
of ğ‘˜ pairwise distinct positive integers. In the second line, output ğ‘˜ pairwise distinct positive integers
that sum up to ğ‘› (if there are many such representations, output any of them).

| *Input*     |                                                   |
|-------------+---------------------------------------------------|
| First Line  | Given an integer n                                |


| *Output*      | In the first line, output the maximum number ğ‘˜ such that ğ‘› can be represented as a sum
                  of ğ‘˜ pairwise distinct positive integers. In the second line, output ğ‘˜ pairwise distinct positive integers
                  that sum up to ğ‘› (if there are many such representations, output any of them).                             |
| *Constraints* | 1 â‰¤ ğ‘› â‰¤ 10**9                                                                                              |

** Example Values


| Limit  | Value     |
|--------+-----------|
| Time   | 5 seconds |
| Memory | 512 Mb    |
